//------------------------------------------------------------------------------
// <auto-generated>
//     Цей код створено засобом.
//     Зміни в цьому файлі буде втрачено при повторній генерації.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReadFlow.Properties
{
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase
    {
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

        public static Settings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        /// <summary>Технічна назва обраної теми (імʼя файлу з Themes/ без розширення).</summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("light")]
        public string Theme
        {
            get
            {
                return ((string)(this["Theme"]));
            }
            set
            {
                this["Theme"] = value;
            }
        }

        /// <summary>Розмір шрифту тексту. 0 — брати значення з теми.</summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double FontSize
        {
            get
            {
                return ((double)(this["FontSize"]));
            }
            set
            {
                this["FontSize"] = value;
            }
        }

        /// <summary>Міжрядковий інтервал тексту. 0 — брати значення з теми.</summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double LineHeight
        {
            get
            {
                return ((double)(this["LineHeight"]));
            }
            set
            {
                this["LineHeight"] = value;
            }
        }

        /// <summary>Тривалість заміру в секундах.</summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int TimerSeconds
        {
            get
            {
                return ((int)(this["TimerSeconds"]));
            }
            set
            {
                this["TimerSeconds"] = value;
            }
        }

        /// <summary>Режим підрахунку абзаців (значення <c>ParagraphMode</c>).</summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ParagraphMode
        {
            get
            {
                return ((int)(this["ParagraphMode"]));
            }
            set
            {
                this["ParagraphMode"] = value;
            }
        }

        /// <summary>Спосіб заміру: 0 — клік = стоп, 1 — таймер.</summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int MeasurementMode
        {
            get
            {
                return ((int)(this["MeasurementMode"]));
            }
            set
            {
                this["MeasurementMode"] = value;
            }
        }

        /// <summary>Режим C: відмічати помилки під час читання.</summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MarkErrors
        {
            get
            {
                return ((bool)(this["MarkErrors"]));
            }
            set
            {
                this["MarkErrors"] = value;
            }
        }

        /// <summary>Чи розгорнута ліва панель налаштувань.</summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SettingsExpanded
        {
            get
            {
                return ((bool)(this["SettingsExpanded"]));
            }
            set
            {
                this["SettingsExpanded"] = value;
            }
        }

        /// <summary>Підсвічувати рядок під курсором у режимі читання.</summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LineHighlight
        {
            get
            {
                return ((bool)(this["LineHighlight"]));
            }
            set
            {
                this["LineHighlight"] = value;
            }
        }

        /// <summary>Шрифт, зручніший для читання, замість типового.</summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ReadingFont
        {
            get
            {
                return ((bool)(this["ReadingFont"]));
            }
            set
            {
                this["ReadingFont"] = value;
            }
        }
    }
}
